FILES=init graph level_data level_image direction \
      element empty blow elem_op shot robbo \
      static movable capsule_r collected teleport cannon monsters \
      level info game main
TOP=../..
EXECUTABLE=MLRobbo
include $(TOP)/OMakefile
